// Code generated by MockGen. DO NOT EDIT.
// Source: secrets_manager.go
//
// Generated by this command:
//
//	mockgen -source=secrets_manager.go -package=sdkclient -destination=secrets_manager_mockgen.go
//

// Package sdkclient is a generated GoMock package.
package sdkclient

import (
	context "context"
	reflect "reflect"

	secretsmanager "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretsManager is a mock of SecretsManager interface.
type MockSecretsManager struct {
	ctrl     *gomock.Controller
	recorder *MockSecretsManagerMockRecorder
	isgomock struct{}
}

// MockSecretsManagerMockRecorder is the mock recorder for MockSecretsManager.
type MockSecretsManagerMockRecorder struct {
	mock *MockSecretsManager
}

// NewMockSecretsManager creates a new mock instance.
func NewMockSecretsManager(ctrl *gomock.Controller) *MockSecretsManager {
	mock := &MockSecretsManager{ctrl: ctrl}
	mock.recorder = &MockSecretsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretsManager) EXPECT() *MockSecretsManagerMockRecorder {
	return m.recorder
}

// GetSecretValue mocks base method.
func (m *MockSecretsManager) GetSecretValue(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSecretValue", varargs...)
	ret0, _ := ret[0].(*secretsmanager.GetSecretValueOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretValue indicates an expected call of GetSecretValue.
func (mr *MockSecretsManagerMockRecorder) GetSecretValue(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretValue", reflect.TypeOf((*MockSecretsManager)(nil).GetSecretValue), varargs...)
}
