# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale and it will be closed
  if no further activity occurs. Thank you for your contributions! You can 
  also find us in the \#serverless channel from the 
  [Datadog community Slack](https://chat.datadoghq.com/).
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

