# Title shown in Application Information tab.
title: Datadog Metrics infra
# Sub Title shown in Application Information tab.
description: Setting up infra for sending OCI metrics to Datadog 
schemaVersion: 1.1.0
version: 1.0
locale: en
variableGroups:
  - title: "Tenancy"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
  - title: "Datadog Environment"
    variables:
      - ${datadog_api_key}
      - ${datadog_environment}
  - title: "Network options"
    variables:
      - ${create_vcn}
      - ${vcnCompartment}
      - ${existingVcn}
      - ${function_subnet_id}
  - title: "Function settings"
    variables:
      - ${function_app_shape}
      - ${function_image_path}
      - ${oci_docker_username}
      - ${oci_docker_password}

variables:
  resource_name_prefix:
    type: string
    title: Resource prefix
    description: The prefix for the name of all of the resources.
    required: true
    default: datadog-metrics
  create_vcn:
    title: Create VCN
    description: Optional variable to create virtual network for the setup. Otherwise, choose an existing subnet from VCN
    type: boolean
    default: true

# VCN 
  vcnCompartment:
    # prepopulates available values for compartment
    type: oci:identity:compartment:id
  existingVcn:
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: ${vcnCompartment}
  function_subnet_id:
    title: Function Subnet OCID
    type: oci:core:subnet:id
    description: The OCID of the subnet to be used for the function app. Required if not creating the VCN.
    required: false
    dependsOn:
      compartmentId: ${vcnCompartment}
      vcnId: ${existingVcn}

# Datadog Environment
  datadog_api_key:
    title: Datadog API Key
    type: string
    description: The API key for sending message to datadog endpoints.
    required: true
    sensitive: true
    password: true
    confirmation: true
  datadog_environment:
    title: Datadog Environment Endpoint
    type: enum
    description: The endpoint to hit for sending the metrics. Varies by different datacenter.
    required: true
    enum:
      - ocimetrics-intake.datadoghq.com
      - ocimetrics-intake.us5.datadoghq.com 
      - ocimetrics-intake.us3.datadoghq.com
      - ocimetrics-intake.datadoghq.eu
      - ocimetrics-intake.ap1.datadoghq.com
      - ocimetrics-intake.ddog-gov.com
    allowMultiple: false

  # Function setup
  function_app_shape:
    title: Function Application shape
    type: enum
    description: The shape of the function application. The docker image should be built accordingly. Use GENERIC_ARM if using Oracle Resource managaer stack.
    required: true
    enum:
      - GENERIC_ARM
      - GENERIC_X86
      - GENERIC_X86_ARM
    default: GENERIC_ARM
  function_image_path:
    title: Function Image Path
    type: string
    description: The full path of the function image. The image should be present in the container registry for the region and be compatible with the function application shape.
    required: false
  oci_docker_username:
    title: OCI Docker registry user name
    type: string
    description: The user login for the OCI docker container registry to push function image. Not required if using an existing image path
    required: false
    sensitive: true
  oci_docker_password:
    title: OCI Docker registry password
    type: password
    description: The user password for the OCI docker container registry.
    required: false
    sensitive: true
  service_connector_target_batch_size_in_kbs:
    title: Service Connector hub batch size
    type: nonNegativeInteger
    description: The batch size (in Kb) in which to send payload to target.
    required: false
    default: 5000
