// Code generated by MockGen. DO NOT EDIT.
// Source: kms.go
//
// Generated by this command:
//
//	mockgen -source=kms.go -package=client -destination=kms_mockgen.go
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	kms "github.com/aws/aws-sdk-go-v2/service/kms"
	gomock "go.uber.org/mock/gomock"
)

// MockKMS is a mock of KMS interface.
type MockKMS struct {
	ctrl     *gomock.Controller
	recorder *MockKMSMockRecorder
	isgomock struct{}
}

// MockKMSMockRecorder is the mock recorder for MockKMS.
type MockKMSMockRecorder struct {
	mock *MockKMS
}

// NewMockKMS creates a new mock instance.
func NewMockKMS(ctrl *gomock.Controller) *MockKMS {
	mock := &MockKMS{ctrl: ctrl}
	mock.recorder = &MockKMSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKMS) EXPECT() *MockKMSMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockKMS) Decrypt(ctx context.Context, params *kms.DecryptInput, optFns ...func(*kms.Options)) (*kms.DecryptOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Decrypt", varargs...)
	ret0, _ := ret[0].(*kms.DecryptOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockKMSMockRecorder) Decrypt(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockKMS)(nil).Decrypt), varargs...)
}
