AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pushes RDS Enhanced metrics to Datadog.
Parameters:
  KMSKeyId:
    Type: String
    Description: The id (final part of the key's ARN) of a KMS key used to encrypt and decrypt your Datadog API and App keys. 
  KMSEncryptedKeys:
    Type: String
    Default: 'YOUR_KEY'
    Description: |
      The encrypted value of your Datadog API and APP key in the following format: '{"api_key":"<YOUR_API_KEY>", "app_key":"<YOUR_APP_KEY>"}'

Resources:
  rdslambdaddfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Pushes RDS Enhanced metrics to Datadog.
      Environment:
        Variables:
          kmsEncryptedKeys: !Ref KMSEncryptedKeys
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Policies:
        KMSDecryptPolicy:
          KeyId: !Ref KMSKeyId
      Runtime: python2.7
      Timeout: 10
      KmsKeyArn:
        !Sub
          - 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${keyId}'
          - {keyId: !Ref KMSKeyId}
    Type: AWS::Serverless::Function
