// Code generated by MockGen. DO NOT EDIT.
// Source: kms.go
//
// Generated by this command:
//
//	mockgen -source=kms.go -package=config -destination=kms_mockgen.go
//

// Package config is a generated GoMock package.
package config

import (
	context "context"
	reflect "reflect"

	kms "github.com/aws/aws-sdk-go-v2/service/kms"
	gomock "go.uber.org/mock/gomock"
)

// MockKMSAPIClient is a mock of KMSAPIClient interface.
type MockKMSAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockKMSAPIClientMockRecorder
	isgomock struct{}
}

// MockKMSAPIClientMockRecorder is the mock recorder for MockKMSAPIClient.
type MockKMSAPIClientMockRecorder struct {
	mock *MockKMSAPIClient
}

// NewMockKMSAPIClient creates a new mock instance.
func NewMockKMSAPIClient(ctrl *gomock.Controller) *MockKMSAPIClient {
	mock := &MockKMSAPIClient{ctrl: ctrl}
	mock.recorder = &MockKMSAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKMSAPIClient) EXPECT() *MockKMSAPIClientMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockKMSAPIClient) Decrypt(ctx context.Context, params *kms.DecryptInput, optFns ...func(*kms.Options)) (*kms.DecryptOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Decrypt", varargs...)
	ret0, _ := ret[0].(*kms.DecryptOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockKMSAPIClientMockRecorder) Decrypt(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockKMSAPIClient)(nil).Decrypt), varargs...)
}
