// Code generated by MockGen. DO NOT EDIT.
// Source: secretsmanager.go
//
// Generated by this command:
//
//	mockgen -source=secretsmanager.go -package=config -destination=secretsmanager_mockgen.go
//

// Package config is a generated GoMock package.
package config

import (
	context "context"
	reflect "reflect"

	secretsmanager "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretsManagerAPIClient is a mock of SecretsManagerAPIClient interface.
type MockSecretsManagerAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockSecretsManagerAPIClientMockRecorder
	isgomock struct{}
}

// MockSecretsManagerAPIClientMockRecorder is the mock recorder for MockSecretsManagerAPIClient.
type MockSecretsManagerAPIClientMockRecorder struct {
	mock *MockSecretsManagerAPIClient
}

// NewMockSecretsManagerAPIClient creates a new mock instance.
func NewMockSecretsManagerAPIClient(ctrl *gomock.Controller) *MockSecretsManagerAPIClient {
	mock := &MockSecretsManagerAPIClient{ctrl: ctrl}
	mock.recorder = &MockSecretsManagerAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretsManagerAPIClient) EXPECT() *MockSecretsManagerAPIClientMockRecorder {
	return m.recorder
}

// GetSecretValue mocks base method.
func (m *MockSecretsManagerAPIClient) GetSecretValue(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSecretValue", varargs...)
	ret0, _ := ret[0].(*secretsmanager.GetSecretValueOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretValue indicates an expected call of GetSecretValue.
func (mr *MockSecretsManagerAPIClientMockRecorder) GetSecretValue(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretValue", reflect.TypeOf((*MockSecretsManagerAPIClient)(nil).GetSecretValue), varargs...)
}
