// Code generated by MockGen. DO NOT EDIT.
// Source: ssm.go
//
// Generated by this command:
//
//	mockgen -source=ssm.go -package=config -destination=ssm_mockgen.go
//

// Package config is a generated GoMock package.
package config

import (
	context "context"
	reflect "reflect"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	gomock "go.uber.org/mock/gomock"
)

// MockSSMAPIClient is a mock of SSMAPIClient interface.
type MockSSMAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockSSMAPIClientMockRecorder
	isgomock struct{}
}

// MockSSMAPIClientMockRecorder is the mock recorder for MockSSMAPIClient.
type MockSSMAPIClientMockRecorder struct {
	mock *MockSSMAPIClient
}

// NewMockSSMAPIClient creates a new mock instance.
func NewMockSSMAPIClient(ctrl *gomock.Controller) *MockSSMAPIClient {
	mock := &MockSSMAPIClient{ctrl: ctrl}
	mock.recorder = &MockSSMAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSMAPIClient) EXPECT() *MockSSMAPIClientMockRecorder {
	return m.recorder
}

// GetParameter mocks base method.
func (m *MockSSMAPIClient) GetParameter(ctx context.Context, params *ssm.GetParameterInput, optFns ...func(*ssm.Options)) (*ssm.GetParameterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParameter", varargs...)
	ret0, _ := ret[0].(*ssm.GetParameterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParameter indicates an expected call of GetParameter.
func (mr *MockSSMAPIClientMockRecorder) GetParameter(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParameter", reflect.TypeOf((*MockSSMAPIClient)(nil).GetParameter), varargs...)
}
