// Code generated by "stringer -type ContentType -trimprefix ContentType -output content_string.go"; DO NOT EDIT.

package parsing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContentTypeUnknown-0]
	_ = x[ContentTypeCloudwatchLogs-1]
	_ = x[ContentTypeS3-2]
	_ = x[ContentTypeKinesis-3]
	_ = x[ContentTypeEventBridge-4]
	_ = x[ContentTypeSNS-5]
	_ = x[ContentTypeRetry-6]
}

const _ContentType_name = "UnknownCloudwatchLogsS3KinesisEventBridgeSNSRetry"

var _ContentType_index = [...]uint8{0, 7, 21, 23, 30, 41, 44, 49}

func (i ContentType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ContentType_index)-1 {
		return "ContentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContentType_name[_ContentType_index[idx]:_ContentType_index[idx+1]]
}
