// Code generated by "stringer -type InvocationSource -trimprefix InvocationSource"; DO NOT EDIT.

package parsing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvocationSourceUnknown-0]
	_ = x[InvocationSourceCloudwatchLogs-1]
	_ = x[InvocationSourceS3-2]
	_ = x[InvocationSourceSNS-3]
	_ = x[InvocationSourceSQS-4]
	_ = x[InvocationSourceKinesis-5]
}

const _InvocationSource_name = "UnknownCloudwatchLogsS3SNSSQSKinesis"

var _InvocationSource_index = [...]uint8{0, 7, 21, 23, 26, 29, 36}

func (i InvocationSource) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_InvocationSource_index)-1 {
		return "InvocationSource(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InvocationSource_name[_InvocationSource_index[idx]:_InvocationSource_index[idx+1]]
}
