// Code generated by MockGen. DO NOT EDIT.
// Source: s3_client.go
//
// Generated by this command:
//
//	mockgen -source=s3_client.go -package=parsing -destination=s3_client_mockgen.go
//

// Package parsing is a generated GoMock package.
package parsing

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3APIClient is a mock of S3APIClient interface.
type MockS3APIClient struct {
	ctrl     *gomock.Controller
	recorder *MockS3APIClientMockRecorder
	isgomock struct{}
}

// MockS3APIClientMockRecorder is the mock recorder for MockS3APIClient.
type MockS3APIClientMockRecorder struct {
	mock *MockS3APIClient
}

// NewMockS3APIClient creates a new mock instance.
func NewMockS3APIClient(ctrl *gomock.Controller) *MockS3APIClient {
	mock := &MockS3APIClient{ctrl: ctrl}
	mock.recorder = &MockS3APIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3APIClient) EXPECT() *MockS3APIClientMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockS3APIClient) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockS3APIClientMockRecorder) GetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockS3APIClient)(nil).GetObject), varargs...)
}
