AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pushes logs and metrics from AWS to Datadog.
Resources:
  loglambdaddfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Pushes logs and metrics from AWS to Datadog.
      Handler: lambda_function.lambda_handler
      MemorySize: 1024
      Runtime: python2.7
      Timeout: 120
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Python27:3'
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: "logs:ListTagsLogGroup"
              Resource: "*"
    Type: AWS::Serverless::Function
