# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trace.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import span_pb2 as span__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="trace.proto",
    package="pb",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0btrace.proto\x12\x02pb\x1a\nspan.proto"X\n\x08\x41PITrace\x12\x0f\n\x07traceID\x18\x01 \x01(\x04\x12\x17\n\x05spans\x18\x02 \x03(\x0b\x32\x08.pb.Span\x12\x11\n\tstartTime\x18\x06 \x01(\x03\x12\x0f\n\x07\x65ndTime\x18\x07 \x01(\x03\x62\x06proto3',
    dependencies=[
        span__pb2.DESCRIPTOR,
    ],
)


_APITRACE = _descriptor.Descriptor(
    name="APITrace",
    full_name="pb.APITrace",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="traceID",
            full_name="pb.APITrace.traceID",
            index=0,
            number=1,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="spans",
            full_name="pb.APITrace.spans",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="startTime",
            full_name="pb.APITrace.startTime",
            index=2,
            number=6,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="endTime",
            full_name="pb.APITrace.endTime",
            index=3,
            number=7,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=31,
    serialized_end=119,
)

_APITRACE.fields_by_name["spans"].message_type = span__pb2._SPAN
DESCRIPTOR.message_types_by_name["APITrace"] = _APITRACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

APITrace = _reflection.GeneratedProtocolMessageType(
    "APITrace",
    (_message.Message,),
    {
        "DESCRIPTOR": _APITRACE,
        "__module__": "trace_pb2"
        # @@protoc_insertion_point(class_scope:pb.APITrace)
    },
)
_sym_db.RegisterMessage(APITrace)


# @@protoc_insertion_point(module_scope)
