---
name: AWS Python Integration tests

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: AWS Python integration tests
        run: |
          ./aws/logs_monitoring/tools/integration_tests/integration_tests.sh --python-version=3.13
