name: Integration tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["python3.7", "python3.8"]
    steps:
      - uses: actions/checkout@v2

      - name: Run integration tests
        run: |
          ./aws/logs_monitoring/tools/integration_test.sh ${{ matrix.python-version }}
