name: Integration tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run integration tests
        run: |
          ./aws/logs_monitoring/tools/integration_tests/integration_tests.sh --python-version=${{ matrix.python-version }}
