name: Python unit tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Python unit tests
        env:
          AWS_DEFAULT_REGION: us-east-1
          DD_API_KEY: "11111111111111111111111111111111"
          DD_ADDITIONAL_TARGET_LAMBDAS: "ironmaiden,megadeth"
        run: |
          pip install boto3 mock approvaltests
          python -m unittest discover ./aws/logs_monitoring/
          python -m unittest discover ./aws/rds_enhanced_monitoring/
