name: Trace forwarder tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run trace forwarder tests
        run: |
          ./aws/logs_monitoring/trace_forwarder/scripts/run_tests.sh
