name: Trace forwarder tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Run trace forwarder tests
        run: |
          ./aws/logs_monitoring/trace_forwarder/scripts/run_tests.sh
